name = "chat-widget-proxy"
main = "worker.js"
compatibility_date = "2024-01-01"

[vars]
# The API key is stored as a Cloudflare secret, not here.
# Run: npx wrangler secret put API_KEY

[observability]
enabled = true

