name = "tony-copilot"
main = "worker.js"
compatibility_date = "2025-09-07"
account_id = "59fe..."   # keep your real account_id here
workers_dev = true

# Remove the old Durable Object class named "Chat"
[[migrations]]
tag = "remove-chat-do-1"
deleted_classes = ["Chat"]
