name = "my-chat-agent"
main = "src/worker.js"
compatibility_date = "2024-09-01"
workers_dev = true

[vars]
# Your public system prompt (guardrails). You can point this at the file in your repo:
SYSTEM_URL = "https://tonyabdelmalak.github.io/chat-widget/assets/chat/system.md"

# Allow your site to call the worker (CORS)
ALLOWED_ORIGINS = "https://tonyabdelmalak.github.io"

# GROQ model + behavior (safe defaults)
GROQ_MODEL = "llama-3.1-70b-versatile"
TEMPERATURE = "0.2"
