name = "my-chat-agent"
main = "chat-widget/worker.js"   # <-- path fix

compatibility_date = "2024-09-01"

# (optional but nice to keep)
usage_model = "unbound"

[vars]
ALLOWED_ORIGINS = "https://tonyabdelmalak.github.io,https://tonyabdelmalak.com"

# If you use the AI binding, keep this. If not, remove.
# [ai]
# binding = "AI"

[observability]
enabled = true
